version: '3'

services:
  api:
    build: ./flask-api
    ports:
      - '5000:5000'

  database:
    image: postgres
    volumes:
      - cbk_data:/var/lib/postgresql/data
      - ./cbk.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  cbk_data: