insert into cbk_user (balance, telegram_id) values (13, 1);
insert into cbk_user (balance, telegram_id) values (42, 2);
insert into cbk_user (balance, telegram_id) values (18, 3);
insert into cbk_user (balance, telegram_id) values (38, 4);
insert into cbk_user (balance, telegram_id) values (13, 5);
insert into cbk_user (balance, telegram_id) values (0, 6);
insert into cbk_user (balance, telegram_id) values (47, 7);
insert into cbk_user (balance, telegram_id) values (15, 8);
insert into cbk_user (balance, telegram_id) values (0, 9);
insert into cbk_user (balance, telegram_id) values (0, 10);
insert into cbk_user (balance, telegram_id) values (5, 11);
insert into cbk_user (balance, telegram_id) values (35, 12);
insert into cbk_user (balance, telegram_id) values (9, 13);
insert into cbk_user (balance, telegram_id) values (16, 14);
insert into cbk_user (balance, telegram_id) values (31, 15);
insert into cbk_user (balance, telegram_id) values (6, 16);
insert into cbk_user (balance, telegram_id) values (31, 17);
insert into cbk_user (balance, telegram_id) values (43, 18);
insert into cbk_user (balance, telegram_id) values (3, 19);
insert into cbk_user (balance, telegram_id) values (12, 20);

insert into product (name, category, price, active) values ('Flower - Potmums', 3, 13, false);
insert into product (name, category, price, active) values ('Onions - Green', 2, 9, false);
insert into product (name, category, price, active) values ('Wine - Jafflin Bourgongone', 1, 16, true);
insert into product (name, category, price, active) values ('Duck - Breast', 1, 15, true);
insert into product (name, category, price, active) values ('Kale - Red', 3, 7, false);
insert into product (name, category, price, active) values ('Pants Custom Dry Clean', 3, 5, false);
insert into product (name, category, price, active) values ('Bagel - Ched Chs Presliced', 2, 9, false);
insert into product (name, category, price, active) values ('Wine - Cotes Du Rhone Parallele', 1, 18, false);
insert into product (name, category, price, active) values ('Cheese - Mix', 1, 15, false);
insert into product (name, category, price, active) values ('Calvados - Boulard', 2, 18, true);
insert into product (name, category, price, active) values ('Sage Ground Wiberg', 2, 8, false);
insert into product (name, category, price, active) values ('Capers - Pickled', 3, 16, true);
insert into product (name, category, price, active) values ('Wine - Duboeuf Beaujolais', 1, 6, true);
insert into product (name, category, price, active) values ('Basil - Dry, Rubbed', 2, 19, false);
insert into product (name, category, price, active) values ('7up Diet, 355 Ml', 1, 4, true);
insert into product (name, category, price, active) values ('Nantucket - 518ml', 1, 7, true);
insert into product (name, category, price, active) values ('Muffin Mix - Lemon Cranberry', 2, 5, false);
insert into product (name, category, price, active) values ('Beef - Top Sirloin - Aaa', 1, 5, true);
insert into product (name, category, price, active) values ('Seedlings - Clamshell', 3, 11, true);
insert into product (name, category, price, active) values ('Turnip - Wax', 3, 9, false);

