# Generated by Django 3.0.2 on 2020-02-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
