# Generated by Django 3.0.2 on 2020-02-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0002_auto_20200202_1808'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cbkuser',
            table='cbk_user',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
