# Generated by Django 3.0.2 on 2020-02-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0003_auto_20200202_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
