# Generated by Django 3.0.2 on 2020-02-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0004_auto_20200202_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbkuser',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
