# Generated by Django 3.0.2 on 2020-02-02 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.DO_NOTHING, to='balancekeeper.Category'),
        ),
    ]
