# Generated by Django 3.0.2 on 2020-02-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0007_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cbk_user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
