# Generated by Django 3.0.2 on 2020-02-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0013_category_cbkuser_product_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cbk_user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CbkUser',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
