# Generated by Django 3.0.2 on 2020-02-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0016_auto_20200202_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbkuser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
