# Generated by Django 3.0.2 on 2020-02-10 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('balancekeeper', '0018_auto_20200209_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='balancekeeper.Category'),
        ),
    ]
